SteamBoat\SteamBoatBundle\Entity\SteamGameStorage:
    type: entity
    table: null
    repositoryClass: SteamBoat\SteamBoatBundle\Entity\SteamGameStorageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        appId:
            type: integer
        logoUrl:
            type: string
            length: 256
            nullable: TRUE
        name:
            type: string
            length: 128
    lifecycleCallbacks: {  }
