SteamBoat\SteamBoatBundle\Entity\SteamIdStorage:
    type: entity
    table: null
    repositoryClass: SteamBoat\SteamBoatBundle\Entity\SteamIdStorageRepository
    uniqueConstraints:
        steamId64:
            columns: steamId64
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        customUrl:
            type: string
            length: 256
        fetchTime:
            type: integer
        limited:
            type: boolean
        nickname:
            type: string
            length: 128
#        playTimes:
#            type: array...
        steamId64:
            type: string
            length: 64
        tradeBanState:
            type: string
            length: 64
    manyToMany:
        friends:
            targetEntity: SteamIdStorage
            joinTable:
                name: SteamIds_Friends
                joinColumns:
                    steamId_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    friend_id:
                        referencedColumnName: id
        games:
            targetEntity: SteamGameStorage
            joinTable:
                name: SteamIds_SteamGames
                joinColumns:
                    steamId_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    game_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
