<?php

namespace SteamBoat\SteamBoatBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SteamCondenser\Community\SteamGame;

/**
 * SteamGameStorageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SteamGameStorageRepository extends EntityRepository
{

/**
 * Retrieve a SteamGame by AppID.
 *
 * @param $appId
 * @return object|null
 */
    public function findOneByAppId($appId) {
        // Check local cache.
        $steamGame = $this->findOneBy(
            ['appId' => $appId]
        );
        if ($steamGame === null) {
            // Fetch remotely.
        }
        return $steamGame ?: null;
    }

    /**
     * Saves Steam games.
     *
     * @param SteamGame $steamGameData
     *   The Steam game to store.
     *
     * @return SteamGameStorage
     *   Doctrine storage entity.
     */
    public function createSteamGameStorage($steamGameData) {
        $steamGameStorage = new SteamGameStorage();

        // Map properties.
        foreach ($steamGameData as $property => $value) {
            $steamGameStorage->{'set' . $property}($value);
        }

        $entityManager = $this->getEntityManager();
        $entityManager->persist($steamGameStorage);
        return $steamGameStorage;
    }

}
