<?php

namespace SteamBoat\SteamBoatBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SteamCondenser\Community\SteamGame;

/**
 * SteamGameStorageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SteamGameStorageRepository extends EntityRepository
{

/**
 * Retrieve a SteamGame by AppID.
 *
 * @param $appId
 * @return object|null
 */
    public function findOneByAppId($appId) {
        // Check local cache.
        $steamGame = $this->findOneBy(
            array('appId' => $appId)
        );
        if ($steamGame === null) {
            // Fetch remotely.
        }
        return $steamGame ? $steamGame : null;
    }

    /**
     * @param SteamGame $steamGame
     * @return SteamGameStorage
     */
    public function createSteamGameStorage(SteamGame $steamGame) {
        $steamGameStorage = new SteamGameStorage();

        // Map properties.
        $steamGameStorage->setName($steamGame->getName());
        $steamGameStorage->setAppId($steamGame->getAppId());
        $steamGameStorage->setLogoUrl($steamGame->getLogoUrl());

        $em = $this->getEntityManager();
        $em->persist($steamGameStorage);
        return $steamGameStorage;
    }
}
