<?php

namespace SteamBoat\SteamBoatBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * SteamIdStorageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SteamIdStorageRepository extends EntityRepository
{

/**
 * Retrieve a SteamId by Nickname. Fetches friends.
 *
 * @param $nickname
 * @return object|null
 */
    public function findOneByNickname($nickname) {
        // Check local cache.
        $steamIdStorage = $this->findOneBy(['nickname' => $nickname]);

        return $steamIdStorage ?: null;
    }

/**
 * Retrieve a SteamId by SteamId64. Does not fetch friends by default.
 *
 * @param $steamId64
 * @return object|null
 */
    public function findOneBySteamId64($steamId64) {
        // Check local cache.
        $steamIdStorage = $this->findOneBy(['steamId64' => $steamId64]);

        return $steamIdStorage ?: null;
    }

    /**
     * @param $steamId
     * @return object|null
     */
    public function createSteamIdStorage($steamIdData) {
        $entityManager = $this->getEntityManager();

        $relatedEntities = [
            'Friends',
            'Games',
        ];

        // Map the entity properties.
        $steamIdStorage = new SteamIdStorage();

        // Handle regular properties and related entities.
        foreach ($steamIdData as $property => $value) {
            if (in_array($property, $relatedEntities)) {
                $this->{'add' . $property}($steamIdStorage, $value);
            }
            else {
                $steamIdStorage->{'set' . $property}($value);
            }
        }

        $entityManager->persist($steamIdStorage);
        return $steamIdStorage;
    }

    /**
     * @param $steamIdStorage
     * @return object|null
     */
    public function writeSteamIdStorage($steamIdStorage) {
        // Cache the steamId in the database.
        $entityManager = $this->getEntityManager();
        $entityManager->flush();
        return $steamIdStorage;
    }

    /**
     * @param $steamIdStorage
     * @param $games
     * @return object|null
     */
    public function addGames(&$steamIdStorage, $games) {
        $entityManager = $this->getEntityManager();

        // Map games.
        $gameStorageRepository = $entityManager->getRepository('SteamBoatBundle:SteamGameStorage');
        if ($games) {
            foreach ($games as $game) {
                // Check for existing game.
                // @TODO Use array.
                if ($existingGame = $gameStorageRepository->findOneByAppId($game['AppId'])) {
                    $steamIdStorage->addGame($existingGame);
                }
                else {
                    $steamIdStorage->addGame($gameStorageRepository->createSteamGameStorage($game));
                }
            }
        }
        // Avoid race conditions where games are added multiple times by flushing regularly.
        $gameStorageRepository->getEntityManager()->flush();

        return $steamIdStorage;
    }

    /**
     * @param $steamIdStorage
     * @param $friends
     * @return object|null
     */
    public function addFriends(&$steamIdStorage, $friends) {
        // Add friends.
        foreach ($friends as $friend) {
            if (isset($friend)) {
                $steamIdStorage->addFriend($friend);
            }
        }
        return $steamIdStorage;
    }
}
