steam_boat_homepage:
    path:  /steam
    defaults: { _controller: SteamBoatBundle:Default:index }
steam_boat_list_games:
    path:  /steam/{name}
    defaults: { _controller: SteamBoatBundle:Default:listGames }
