parameters:
#    steam_boat.example.class: SteamBoat\SteamBoatBundle\Example

services:
    steam_boat.steamid:
        class: SteamBoat\SteamBoatBundle\Service\SteamId
        arguments: [%steam_boat.steam.webapi_key%, @doctrine]

#    steam_boat.example:
#        class: %steam_boat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
